version: '3'

volumes:
  node_modules:
  pg_data:

services:
  postgres:
    image: postgres:12.4-alpine
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pg_data:/var/lib/postgresql/data
